# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch17-local-multiplayer-and-networking-basics/03-a-minimal-working-example-networked-pong-over-local-sockets.py — generated by tools/book-code-repo.

Runs the file as a script in a subprocess and asserts a clean exit, which
catches import errors, syntax errors, and unhandled exceptions in the
top-level example code.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch17-local-multiplayer-and-networking-basics/03-a-minimal-working-example-networked-pong-over-local-sockets.py"))


def test_runs_cleanly():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    result = subprocess.run([sys.executable, SRC], capture_output=True,
                            text=True, timeout=30)
    assert result.returncode == 0, (
        f"{SRC} exited {result.returncode}:\n{result.stderr}"
    )


def test_pure_functions_are_importable_and_callable():
    """Best-effort smoke check for zero-arg top-level functions found in the source."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("_mod", SRC)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    for name in ['run_server']:
        fn = getattr(mod, name, None)
        if callable(fn):
            fn()  # must not raise
