# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch17-local-multiplayer-and-networking-basics/03-a-minimal-working-example-networked-pong-over-local-sockets.py — generated by tools/book-code-repo.

This file contains a real, blocking Pygame event loop (`while running:`
/ `while True:` reading `pygame.event.get()`), which only exits on a
window-close event a headless test can never deliver — running it to
completion isn't possible in CI. Compiling it instead still catches
syntax errors and other mistakes a reader could introduce by mistyping
the listing, without hanging on the loop itself.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch17-local-multiplayer-and-networking-basics/03-a-minimal-working-example-networked-pong-over-local-sockets.py"))
REPO_ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)


def test_pure_functions_are_importable_and_callable():
    """Best-effort smoke check for zero-arg top-level functions found in the source."""
    import importlib.util
    import sys
    # Same REPO_ROOT-on-sys.path reasoning as test_runs_cleanly
    # above (when present) — a snippet that imports this book's
    # own engine/ package needs it importable here too.
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
    spec = importlib.util.spec_from_file_location("_mod", SRC)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    for name in ['run_server']:
        fn = getattr(mod, name, None)
        if callable(fn):
            fn()  # must not raise
