# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch08-space-invaders-waves-formations-and-escalation/07-wave-progression-and-a-how-far-can-you-get-loop.py — generated by tools/book-code-repo.

This snippet has no `if __name__ == "__main__":` guard, blocking event
loop, or display-mode call — the markers this tool uses to recognize a
standalone, complete example — so it's treated as a deliberate excerpt
that may assume an import or variable established earlier in its
chapter's prose (see the book model's own step (c) rule), rather than
asserted to run to a clean exit on its own. A syntax check still catches
a genuine typo or syntax error.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch08-space-invaders-waves-formations-and-escalation/07-wave-progression-and-a-how-far-can-you-get-loop.py"))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)
