# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch06-breakout-bricks-bounces-and-levels/09-lives-level-progression-and-a-simple-level-editor-mini-tool.py — generated by tools/book-code-repo.

This file contains a real, blocking Pygame event loop (`while running:`
/ `while True:` reading `pygame.event.get()`), which only exits on a
window-close event a headless test can never deliver — running it to
completion isn't possible in CI. Compiling it instead still catches
syntax errors and other mistakes a reader could introduce by mistyping
the listing, without hanging on the loop itself.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch06-breakout-bricks-bounces-and-levels/09-lives-level-progression-and-a-simple-level-editor-mini-tool.py"))
REPO_ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)
