# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch10-pac-man-mazes-pellets-and-ghost-ai/09-handling-the-tunnel-wraparound-in-a-maze-context.py — generated by tools/book-code-repo.

Runs the file as a script in a subprocess and asserts a clean exit, which
catches import errors, syntax errors, and unhandled exceptions in the
top-level example code.
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch10-pac-man-mazes-pellets-and-ghost-ai/09-handling-the-tunnel-wraparound-in-a-maze-context.py"))


def test_runs_cleanly():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    result = subprocess.run([sys.executable, SRC], capture_output=True,
                            text=True, timeout=30)
    assert result.returncode == 0, (
        f"{SRC} exited {result.returncode}:\n{result.stderr}"
    )
