# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch07-snake-growth-grids-and-self-collision/09-why-a-list-is-the-right-data-structure-and-when-it-stops-being-one.py — generated by tools/book-code-repo.

This snippet has no `if __name__ == "__main__":` guard, blocking event
loop, or display-mode call — the markers this tool uses to recognize a
standalone, complete example — so it's treated as a deliberate excerpt
that may assume an import or variable established earlier in its
chapter's prose (see the book model's own step (c) rule), rather than
asserted to run to a clean exit on its own. A syntax check still catches
a genuine typo or syntax error.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch07-snake-growth-grids-and-self-collision/09-why-a-list-is-the-right-data-structure-and-when-it-stops-being-one.py"))
REPO_ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)
