# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch18-performance-profiling-and-shipping-your-game/01-profiling-a-pygame-loop-and-reading-what-the-numbers-actually-mean.py — generated by tools/book-code-repo.

This snippet has no `if __name__ == "__main__":` guard, blocking event
loop, or display-mode call — the markers this tool uses to recognize a
standalone, complete example — so it's treated as a deliberate excerpt
that may assume an import or variable established earlier in its
chapter's prose (see the book model's own step (c) rule), rather than
asserted to run to a clean exit on its own. A syntax check still catches
a genuine typo or syntax error.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch18-performance-profiling-and-shipping-your-game/01-profiling-a-pygame-loop-and-reading-what-the-numbers-actually-mean.py"))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)


def test_pure_functions_are_importable_and_callable():
    """Best-effort smoke check for zero-arg top-level functions found in the source."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("_mod", SRC)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    for name in ['run_profiled']:
        fn = getattr(mod, name, None)
        if callable(fn):
            fn()  # must not raise
