# AUTO-GENERATED by book-code-repo — safe to regenerate
"""Smoke test for ../../ch02-the-game-loop-pygame-s-beating-heart/01-events-update-render-the-three-phase-loop-pattern.py — generated by tools/book-code-repo.

This file contains a real, blocking Pygame event loop (`while running:`
/ `while True:` reading `pygame.event.get()`), which only exits on a
window-close event a headless test can never deliver — running it to
completion isn't possible in CI. Compiling it instead still catches
syntax errors and other mistakes a reader could introduce by mistyping
the listing, without hanging on the loop itself.
"""
import os
import py_compile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "../../ch02-the-game-loop-pygame-s-beating-heart/01-events-update-render-the-three-phase-loop-pattern.py"))


def test_compiles():
    assert os.path.isfile(SRC), f"missing source file: {SRC}"
    py_compile.compile(SRC, doraise=True)
